### ISSUE TITLE
`here` variables for sequences and other operators

### ISSUE THREAD

**Issue by anatoliykmetyuk** [scala-subscript/subscript-core#6]
Currently, we don't have them for these nodes. This leads to the problem that we won't be able to use implicit conversions on local variables. For example:
```scala
implicit script printInt(x: Int) = println(x)
script foo = var x: Int
             x
```
In order to find an implicit conversion for `x`, script `foo` will expand to:
```scala
seq(varDef(...), x.at(here).value)
```
Since `here` is not defined in that scope, we won't be able to get that value of `x` - and find an implicit conversion.

FTTB, hence, script will expand to:
```scala
seq(varDef(...), x)
```
but this behaviours should be changed in future, since it is not intuitive.

**EDIT:** the former behaviour will be left FTTB, to preserve the code and since it is not harmful.

**Comment by AndreVanDelft** [comment]
I think 'here' does not need to be in scope for sequences and such operators, but it should be for many other constructs. In the example, the ```x``` is such a construct (a call).

**Comment by anatoliykmetyuk** [comment]
Implicits reworked, `here` for operators no longer needed.
